### ISSUE TITLE
skip "select header row" and "match columns" stage and directly move to "validate data" stage

### ISSUE THREAD

**Issue by SubhasmitaLMG** [UgnisSoftware/react-spreadsheet-import#226] opened 2023-11-20 11:55 UTC
@masiulis Can I skip "select header row" and "match columns" stage and directly move to "validate data" stage?
Means "file upload" and  "validate data" stage should be there only.
Can I do that?

**Comment by masiulis** [comment] 2023-11-20 14:36
Hey @SubhasmitaLMG seems like a duplicate of #188. It will be possible once that one is done. As always PRs are welcome!

**Closed by masiulis** 2023-11-20 14:36 UTC

**Comment by rishabhjindalcred** [comment] 2023-12-29 05:51
@masiulis Could you please provide an example for the above? I am having difficulty understanding how to use the 'skip headers' feature.
