### ISSUE TITLE
I currently need to add @chakra-ui/react, @chakra-ui/system, and framer-motion to my package.json

### ISSUE THREAD

**Issue by lcahlander** [UgnisSoftware/react-spreadsheet-import#124] opened 2022-07-19 14:49 UTC
When I run a `npm run build` it shows that I need to add the following to my package.json in order to build.  

* @chakra-ui/react
* @chakra-ui/system
* framer-motion

These should be automatically included in the build without adding them into my package.json.

**Comment by masiulis** [comment] 2022-07-19 14:50
Heu @lcahlander could you check what npm version you are using by running `npm --version`?

**Comment by lcahlander** [comment] 2022-07-25 18:00
I am also getting an error message on `npm install` from our corporate servers.

```
8233 warn tarball tarball data for @chakra-ui/icon@https://xxx.xxx.xxx:443/artifactory/api/npm/npm-virtual/@chakra-ui/icon/-/icon-3.0.4.tgz (sha512-9Ry+fa6EKRYUexffvgOJ9dRIkxCSnASgdSnb09EbQTgCTeM+47LUsxR2+r8pbY6ZT5D4m2zRLkTrv7O7icoyOw==) seems to be corrupted. Trying again.
```

corporate server domain commented out.

**Comment by masiulis** [comment] 2022-07-25 18:18
Hey, @lcahlander I really have no experience with artifactory. Is it possible to reproduce this bug locally?

**Comment by moisesguilherme** [comment] 2022-09-24 12:03
I struggled installing react-spreadsheet-import component in my project which I created with create-react-app. I tried to install @chakra-ui separately before but it didn't succeed. I downgrade "framer-motion" to "4.1.17 as well.

When my project was created with create-react-app it used react-scripts old version  "4.0.3" and I changed to 5.0.1 which works well. But in this current project I can’t upgrade it, because other libs depend on the old version and they end up breaking. If I upgrade to 5 I will need to change babel and webpack  which was created by create-react-app and I had a hard time doing this. Can anybody help me to use react-spreadsheet-import with these configurations?


node version
v18.1.0

npm version
8.16.0

yarn version
1.22.19

`  "dependencies": {
“react": "^17.0.2"
“react-dom": "^17.0.2"
	“react-scripts": "4.0.3",
"framer-motion": "4.1.17",
"@types/react": "^17.0.14",
    	"@types/react-dom": "^17.0.9",
	"react-spreadsheet-import": "^2.0.8",
}
`

**Comment by lukerollans** [comment] 2022-10-12 07:32
Personally, I'd say `peerDependencies` is correct - the developer opting in to this library should install Chakra UI themselves and the `README` should include the necessary instructions.

The only alternative is to move Chakra back to `dependencies`.

However, @masiulis I think this depends on how you want to market this package. Is it..

1. A spreadsheet import package for _React_; or
2. A spreadsheet import package for _Chakra_ which just so happens to be a React UI framework

The `README`'s introduction made me assume the latter. If so, it's understandable the name `react-spreadsheet-import` might be confusing some folk, as opposed to something like `chakra-spreadsheet-import`

**Comment by hamaadsenpai** [comment] 2022-10-21 14:05
Hi, I don't know if this belongs here. But I'm getting this error. Any fix to this? 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@0.1.0
npm ERR! Found: @chakra-ui/react@2.3.6
npm ERR! node_modules/@chakra-ui/react
npm ERR!   @chakra-ui/react@"^2.3.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @chakra-ui/react@"^1.8.8" from react-spreadsheet-import@2.0.8
npm ERR! node_modules/react-spreadsheet-import
npm ERR!   react-spreadsheet-import@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by masiulis** [comment] 2023-05-24 16:41
This should no longer be needed in >4.0.0.

**Closed by masiulis** 2023-05-24 16:41 UTC
