### ISSUE TITLE
I have input select and has options but my valid data is also shown in unmatch ?

### ISSUE THREAD

**Issue by abhishekchauhan-ipseity** [UgnisSoftware/react-spreadsheet-import#215] opened 2023-11-02 09:09 UTC
I am using this   {
      label: "Country",
      key: "country",
      fieldType: {
        type: "select",
        options: [     { label: "United States", value: "USA" },
        { label: "Canada", value: "Canada"},
        { label: "United Kingdom", value: "UK" },
        { label: "Australia", value: "Australia" },
        { label: "Other", value: "Other" }],
      },
      example: "Select your country",
      validations: [
        {
          rule: "required",
          errorMessage: "Country selection is required",
          level: "error",
        },
      ],
    },
    and in my csv i have Canada data but it show that Canada  is in unmatched data why ? does we have to write any validation rule if we want to pass valid data and gives select option only for invalid data ??

**Comment by masiulis** [comment] 2023-11-03 08:59
Hey @abhishekchauhan-ipseity this sounds like a duplicate of https://github.com/UgnisSoftware/react-spreadsheet-import/issues/141 if I understand correctly. If not feel free to reopen a ticket with an example file and configuration.

**Closed by masiulis** 2023-11-03 08:59 UTC
